
###
POST http://127.0.0.1:7900/api/v1/crawler
Content-Type: application/json

{
    "url": "https://www.komputronik.pl/category/1251/monitory.html",
    "list_selector": "div[ng-if=\"!$ctrl.isFiltered && $ctrl.productsCount > 0\"] div[class=\"tests-product-entry\"]",
    "config": {
        "title": {"allow_missing": false},
        "price": {"allow_missing": false},
        "url": {"allow_missing": false, "attribute": "href"}
    },
    "selectors": {
        "title": "h2[class=\"font-headline text-lg font-bold leading-6 line-clamp-3 md:text-xl md:leading-8\"] a",
        "url": "h2[class=\"font-headline text-lg font-bold leading-6 line-clamp-3 md:text-xl md:leading-8\"] a",
        "price": "div[class=\"text-3xl font-bold leading-8\"]"
    }
}

###
POST http://127.0.0.1:7900/api/v1/data/save/
Content-Type: application/json

[
  {
    "title": "Samsung Odyssey G5 LS27CG552EUXEN - 27'' | VA Curved | QHD | 165Hz",
    "url": "https://www.komputronik.pl/product/885639/monitor-samsung-ls27cg552euxen.html",
    "price": 1099.0
  },
  {
    "title": "OMEN 25i FHD IPS 165Hz 1ms Gaming",
    "url": "https://www.komputronik.pl/product/735559/hp-omen-25i.html",
    "price": 699.0
  },
  {
    "title": "ASUS VG24VQ1B - 23.8'' | VA Curved | Full HD | 1ms | 165Hz",
    "url": "https://www.komputronik.pl/product/797735/asus-vg24vq1b.html",
    "price": 799.0
  }
]