# Generated by Django 4.2.6 on 2024-02-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='strike_price',
        ),
        migrations.CreateModel(
            name='BrandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('strike_price', models.IntegerField(blank=True, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.brand')),
            ],
        ),
    ]
