# Generated by Django 4.2.6 on 2024-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_remove_brand_price_remove_brand_strike_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddetails',
            name='price',
            field=models.FloatField(),
        ),
    ]
