# Generated by Django 4.2.6 on 2024-02-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_branddetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddetails',
            name='strike_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
