# Generated by Django 4.2.6 on 2024-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_branddetails_strike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='branddetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='branddetails',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
