# Generated by Django 4.2.6 on 2024-03-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_alter_brand_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branddetails',
            old_name='title',
            new_name='brand',
        ),
    ]
